### ISSUE TITLE
it's supported for 2.6.0 ?

### ISSUE THREAD

**Issue by dev-jw** [DimaRU/FastDDSPrebuild#1]
Hello，
I want to use Fast-DDS，I choose the version is 2.6.0，But this project can't build Fast-DDS For iOS.
So，it's supported for 2.6.0 ?

If not supported，can you help me How to change

**Comment by DimaRU** [comment]
Hello
It's possible to support 2.6.0. I'll be able to commit a solution in a couple of days. You may start development with 2.1.0 right now.

**Comment by dev-jw** [comment]
Thank you for your reply
I tried to compile it myself. I use 「[ios-cmake](https://github.com/leetal/ios-cmake)」 replace yours.

this is my project : https://github.com/dev-jw/FastDDSPrebuild

on Macos, both  built successfully.

on iOS, No architecture can succeed.  Because the header file 「#include <net/if_arp.h>」 in 「IPFinder.cpp」 is missing 

「#include <net/if_arp.h>」is added since version 2.2.0

**Comment by DimaRU** [comment]
Version 2.6.0 supported now.

**Comment by dev-jw** [comment]
It's really great.  Thank you !

For iOS，I found the architecture missing what the armv7 & armv7s.

And, I try to build by using your scripts. Just the 「macos」 is successed, others are failed.

the error is: 「Force to support stdc++11 but not supported by the compiler」. 

So, Can you help me?
